fix: wrong `helm upgrade` usage in "Installing Brigade"
The `Installing Brigade` document says that you should run `helm upgrade -n brigade-server brigade/brigade` to upgrade it, but it doesn't work:

```
$ helm upgrade -n brigade brigade/brigade --set brigade-github-app.enabled=true
Error: unknown shorthand flag: 'n' in -n
```

I believe the correct command should be `helm upgrade brigade ...` without `-n`, assuming you want to upgrade the release `brigade-server` with the latest version of the chart `brigade/brigade`.

Signed-off-by: Yusuke KUOKA <ykuoka@gmail.com>